name: Auto Label Issue

on:
  issues:
    types: [opened, reopened, edited]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label Issue with Blue Color
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = context.payload.issue;
            const issueBody = issue.body ? issue.body.toLowerCase() : '';
            const issueTitle = issue.title.toLowerCase();

            // Function to create or update a label with a blue color
            const createOrUpdateLabel = async (label) => {
              try {
                await github.rest.issues.getLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label
                });
                // Update label color if it exists
                await github.rest.issues.updateLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label,
                  color: '1E90FF'  // Blue color hex code
                });
              } catch (error) {
                // Create label if it does not exist
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label,
                  color: '1E90FF',  // Blue color hex code
                  description: `Automatically added label`
                });
              }
            };

            // Define labels and colors
            const labels = ['gssoc-ext', 'hacktoberfest-accepted'];
            
            // Loop through labels and apply blue color
            for (const label of labels) {
              await createOrUpdateLabel(label);
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: [label]
              });
            }
