name: Limit Issues Per User

on:
  issues:
    types: [opened]

jobs:
  limit-issues:
    runs-on: ubuntu-latest
    steps:
    - name: Check for existing open issues by the same user
      id: check_issues
      uses: actions/github-script@v6
      with:
        script: |
          const issues = await github.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            creator: context.payload.issue.user.login
          });

          if (issues.data.length > 1) {
            return true;
          } else {
            return false;
          }
        result-encoding: json

    - name: Close the issue if another issue is open
      if: steps.check_issues.outputs.result == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          await github.issues.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            state: 'closed'
          });

          await github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: 'You already have an open issue. Please resolve or close your existing issue before raising another one.'
          });
