name: Duplicate Issue Detector

on:
  issues:
    types: [opened]

jobs:
  detect-duplicate:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Duplicate Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=open" > issues.json

          duplicate_found=false

          # Loop through existing issues and check for similar titles or body content
          for row in $(jq -c '.[]' issues.json); do
            title=$(echo "$row" | jq -r '.title')
            body=$(echo "$row" | jq -r '.body')
            issue_number=$(echo "$row" | jq -r '.number')

            # Check if the title or body has similarities (e.g., keyword matches)
            if [[ "$title" == *"$ISSUE_TITLE"* || "$body" == *"$ISSUE_BODY"* ]]; then
              duplicate_found=true
              DUPLICATE_NUMBER="$issue_number"
              break
            fi
          done

          if [ "$duplicate_found" = true ]; then
            # Comment on the new issue if it's a duplicate
            COMMENT_BODY="This issue appears to be a duplicate of issue #$DUPLICATE_NUMBER. Please refer to the original issue for more information."

            curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"body\":\"$COMMENT_BODY\"}" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
          fi
